### ISSUE TITLE
VMX_PT is not loaded

### ISSUE THREAD

**Issue by Marsman1996** [RUB-SysSec/redqueen#2]
Hi, I tried to install redqueen in my server but it failed.

The OS of my server is Ubuntu 16.04.6  (I tried in both 32bit and 64bit OS.)
& the CPU is Intel Xeon Processor (Skylake, IBRS)

I run the `install.sh` script and everything seems OK.  
But when I run the cmd `python ~/redqueen/kAFL-Fuzzer/kafl_user_prepare.py --recompile -args=/A -file=/A ~/redqueen/Evaluation/lava/binaries/who ~/redqueen/Evaluation/lava/packed/who/ m64`, it shows:

```
kernel AFL: A feedback-driven general purpose ring-0 and ring-3 interface fuzzer for x86 / x86-64 code.

Sergej Schumilo         <sergej@schumilo.de>
Cornelius Aschermann    <cornelius.aschermann@rub.de>
Robert Gawlik           <robert.gawlik@rub.de>

Version: 0.2 (Redqueen)

(C) 2018
<< ~/redqueen/kAFL-Fuzzer/kafl_user_prepare.py: kAFL Binary Packer for Userspace Fuzzing >>

[ERROR]   VMX_PT is not loaded!
```

The problem seems like https://github.com/RUB-SysSec/kAFL/issues/10?

Thanks for any reply.

**Comment by scucat** [comment]
so,how to solve this problem?

**Comment by Marsman1996** [comment]
> so,how to solve this problem?

No, I haven't solved this problem.

**Comment by ITWOI** [comment]
I have the same problem and I solve it by changing the boot kernel to 4.6.2 when booting the system.
